name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -f config/docker/Dockerfile -t openmcp-cardano:latest .
