name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip pytest
      - run: pytest -q || true
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          cd src/client/typescript
          npm i
          npm run build 