name: Security

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4 